// swift-tools-version:5.7
// GENERATED by ./gradlew :dist:ios-framework:updateSwiftPackage -- do not edit by hand.
//
// Uncial ships to SPM as a prebuilt static XCFramework: the sources are Kotlin, so
// there is nothing here for SwiftPM to compile. The URL points at the GitHub Release
// asset for this version's tag, and the checksum is of that exact zip.
// This is a SNAPSHOT manifest: the release asset it names does not exist. Regenerate
// it on the release version before tagging.
import PackageDescription

let package = Package(
    name: "Uncial",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "Uncial", targets: ["Uncial"]),
    ],
    targets: [
        .binaryTarget(
            name: "Uncial",
            url: "https://github.com/andrew-malitchuk/uncial-kmp/releases/download/v0.1.0-SNAPSHOT/Uncial-0.1.0-SNAPSHOT.xcframework.zip",
            checksum: "2f01c54f1a7fccff76fca2f99581fa5b6a5ebb2da119645101c1a8c4efe56a95"
        ),
    ]
)
