// swift-tools-version:5.7
// GENERATED by ./gradlew :dist:ios-framework:updateSwiftPackage -- do not edit by hand.
//
// Uncial ships to SPM as a prebuilt static XCFramework: the sources are Kotlin, so
// there is nothing here for SwiftPM to compile. The URL points at the GitHub Release
// asset for this version's tag, and the checksum is of that exact zip.
import PackageDescription

let package = Package(
    name: "Uncial",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "Uncial", targets: ["Uncial"]),
    ],
    targets: [
        .binaryTarget(
            name: "Uncial",
            url: "https://github.com/andrew-malitchuk/uncial-kmp/releases/download/v0.0.1/Uncial-0.0.1.xcframework.zip",
            checksum: "989f142dff2f021f7031d0529a066deb9624f6bfb693ddb46e6d42a54a7a3e7b"
        ),
    ]
)
