package io.github.andrewmalitchuk.uncial.engine.vision.core.fixture

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * A one-page PDF with a real text layer, embedded as base64.
 *
 * Generated by `./gradlew :samples:cli:run --args="fixture out.pdf --text --ascii --pages 1"`,
 * which forces Helvetica and English so the bytes do not depend on which fonts the
 * generating machine happened to have. Embedded rather than loaded from a file because
 * Kotlin/Native test resources are awkward to locate at runtime, and 1 KB is cheaper than
 * the machinery to avoid it.
 *
 * The iOS test rasterizes this with PDFKit and recognizes it with Vision, which exercises
 * the real iOS pipeline end to end.
 */
@OptIn(ExperimentalEncodingApi::class)
internal val SAMPLE_PDF_BYTES: ByteArray by lazy {
    Base64.decode(
        "JVBERi0xLjYKJfbk/N8KMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovVmVyc2lvbiAvMS42Ci9QYWdlcyAyIDAgUgo+Pgpl" +
        "bmRvYmoKNSAwIG9iago8PAovTGVuZ3RoIDI1NAovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0NCnicdZHBTsMwDIbv" +
        "fQofQZoKGdBuSFy2sRMSEwoPYKVeE9QlleNK7duTbIDKYVfb+r7f9kYXd3sFy0fQx6K6h7pS5Wq1rmvQTXGztdgLMagSdq51" +
        "gh0IjQIdTsS3oL+KV11sLgi1/EWoOUJbF+Gw24NBZkcREJj+cRYQA7xvPyANDt6ToRiRp/Iav1rP+Z/euISLNgxdk9ENOIHG" +
        "MRnpJkCfi31gSZaBDb38LKKT/y3rr3ue5p4DtgTqGcRSol9u0aPYnJrD0NosS90wxOwUd0q7HjHK9UNVD3OBWPQpqgmtd+KC" +
        "X5yz04hGgJMoveE8gn3PYXQnFPqL/g0TP4czDQplbmRzdHJlYW0KZW5kb2JqCjggMCBvYmoKPDwKL0xlbmd0aCAxOTUKL1R5" +
        "cGUgL09ialN0bQovTiA1Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9GaXJzdCAyNwo+PgpzdHJlYW0NCnicVY7LCsIwEEV/5X5B" +
        "p2nTNoIIVhRBBFHBhbiIbZCAJGJa0b932oKPRRb3zOTMTRAjhUwgIWSOHCJPUUAUCuMx7V83A9roiwmgla0Djil/2OIEmvnW" +
        "NRCYTP43QWtTW136J45xFKN72SiLkiJjtZIiUmqkOsNG3w0rkt5IWxN8e6/4khzAzLuG5wFZn4c7C4bc8gcIrvuNQ49+i3bt" +
        "ueljBwWo1MEMk6W5PkxjKw2au8rX1l1AB+umLtgPYOEb8qxOXw0KZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8Ci9MZW5n" +
        "dGggNDAKL1Jvb3QgMSAwIFIKL0lEIFs8QUM4Njk1QzM2MkUzQjYyRUY5RkFFOTA0MDk0RjIzOUYyNDAwQTEzODlEQ0I4NTQ3" +
        "ODQ4OEM0NTlDMzRFRTAwQj4gPEFDODY5NUMzNjJFM0I2MkVGOUZBRTkwNDA5NEYyMzlGMjQwMEExMzg5RENCODU0Nzg0ODhD" +
        "NDU5QzM0RUUwMEI+XQovVHlwZSAvWFJlZgovU2l6ZSAxMAovSW5kZXggWzAgMTBdCi9XIFsxIDIgMV0KL0ZpbHRlciAvRmxh" +
        "dGVEZWNvZGUKPj4Kc3RyZWFtDQp4nGNgYPjPyMDPwMTAAcKMQMzEyOAHYjMDMQsj4zQGRqYDDAA2cAL2DQplbmRzdHJlYW0K" +
        "ZW5kb2JqCnN0YXJ0eHJlZgo3MDQKJSVFT0YK"
    )
}
